DO $$ BEGIN ALTER TYPE "MeasurementState" ADD VALUE IF NOT EXISTS 'SCHEDULED'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "MeasurementState" ADD VALUE IF NOT EXISTS 'COLLECTING'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
