// ---------------------------------------------------------------------------
// Request-to-trace evidence — S6 prerequisite (PD-2).
//
// Every USER message a chat request persists carries the HTTP `traceId` that
// handled the request, in `Message.metadata`. Before this, only the assistant
// reply carried it, so a request could be tied to its trace only by guessing
// from message order — which two overlapping sends in one conversation break,
// and which a failed turn (no assistant reply is stored) cannot do at all.
//
// The traceId is CORRELATION METADATA ONLY. It is generated by the server,
// never taken from the request body, never written into message content, and
// never shown to the model: history is rebuilt from role and content alone.
//
// Branches covered, in the order the route takes them:
//
//   CONFIRM / REJECT / MODIFY   a reply to an active pending action
//   Task path                   `detectWorkRequest` says the turn is work
//   Orchestrator                everything else, success and failure
//
// The route answers only after every write it makes, so each assertion below
// reads the store after the response resolved — there is no timing guess.
// ---------------------------------------------------------------------------

import { describe, it, expect } from "vitest";
import type {
  AICompletionRequest,
  AICompletionResponse,
  AuditEntry,
  AuditLogger,
  Conversation,
  ConversationMessage,
  ConversationStorePort,
  IAIProvider,
  IOrchestrator,
  IToolExecutor,
  JarvisRequest,
  JarvisResponse,
  PendingAction,
  SessionContext,
  ToolExecutionRequest,
  ToolExecutionResult,
} from "@jarvis/core";
import { AgentRegistry, ConversationalAssistant, Orchestrator } from "@jarvis/agents";
import {
  createChatRouter,
  type ChatRouterDeps,
  type PendingActionPort,
  type TaskConversationPort,
} from "../src/routes/chat.js";

// ---------------------------------------------------------------------------
// Fakes
// ---------------------------------------------------------------------------

function memoryConversationStore() {
  const conversations = new Map<string, Conversation>();
  const messages = new Map<string, ConversationMessage[]>();
  let seq = 0;

  const store: ConversationStorePort = {
    async create(input) {
      const id = `conv-${++seq}`;
      const conversation: Conversation = {
        id,
        title: input.title ?? null,
        userId: input.userId,
        agentId: input.agentId ?? null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      conversations.set(id, conversation);
      messages.set(id, []);
      return conversation;
    },
    async findByIdAndUserId(conversationId, userId) {
      const found = conversations.get(conversationId);
      return found && found.userId === userId ? found : null;
    },
    async getMessages(conversationId) {
      return [...(messages.get(conversationId) ?? [])];
    },
    async addMessage(input) {
      const message: ConversationMessage = {
        id: `msg-${++seq}`,
        role: input.role as ConversationMessage["role"],
        content: input.content,
        ...(input.metadata ? { metadata: input.metadata } : {}),
        createdAt: new Date().toISOString(),
      };
      const list = messages.get(input.conversationId) ?? [];
      list.push(message);
      messages.set(input.conversationId, list);
      return message;
    },
  };

  return {
    store,
    /** Every message of every conversation, in write order. */
    all(): ConversationMessage[] {
      return [...messages.values()].flat();
    },
    of(conversationId: string): ConversationMessage[] {
      return messages.get(conversationId) ?? [];
    },
    usersOf(conversationId: string): ConversationMessage[] {
      return this.of(conversationId).filter((m) => m.role === "user");
    },
  };
}

const TOKENS: Record<string, { userId: string; role: "member"; email: string }> = {
  "token-user-1": { userId: "user-1", role: "member", email: "user-1@test.local" },
};

const tokenService = {
  verifyAccessToken: (token: string) => TOKENS[token] ?? null,
} as unknown as ChatRouterDeps["tokenService"];

/** An orchestrator that answers, records what it saw, and never runs a tool. */
function answeringOrchestrator(reply = "Hello from JARVIS") {
  const seen: Array<{ request: JarvisRequest; context: SessionContext }> = [];
  const orchestrator: IOrchestrator = {
    async process(request, context): Promise<JarvisResponse> {
      seen.push({ request, context });
      return {
        success: true,
        data: { message: reply, conversationId: context.conversationId ?? "", agentId: "conversational-assistant" },
        traceId: context.traceId,
        timestamp: new Date().toISOString(),
      };
    },
  };
  return { orchestrator, seen };
}

/** An orchestrator whose turn FAILS — the path that stores no assistant reply. */
function failingOrchestrator(): IOrchestrator {
  return {
    async process(_request, context): Promise<JarvisResponse> {
      return {
        success: false,
        error: { code: "TOOL_EXECUTION_FAILED", message: "Data retrieval failed." },
        traceId: context.traceId,
        timestamp: new Date().toISOString(),
      };
    },
  };
}

/** An orchestrator that THROWS after the user message was already saved. */
function throwingOrchestrator(): IOrchestrator {
  return {
    async process(): Promise<JarvisResponse> {
      throw new Error("boom");
    },
  };
}

const unreachableExecutor: IToolExecutor = {
  async execute(): Promise<never> {
    throw new Error("ToolExecutor was not expected to run in this test");
  },
};

function recordingExecutor() {
  const requests: ToolExecutionRequest[] = [];
  const executor: IToolExecutor = {
    async execute(request): Promise<ToolExecutionResult> {
      requests.push(request);
      return {
        executionId: "exec-1",
        toolId: request.toolId,
        status: "completed",
        result: { success: true, data: { ok: true } },
        startedAt: new Date(),
        completedAt: new Date(),
        durationMs: 1,
      };
    },
  };
  return { executor, requests };
}

function pendingActionFor(conversationId: string): PendingAction {
  return {
    id: "pa-1",
    conversationId,
    userId: "user-1",
    toolId: "meta.adset.budget.update",
    action: "meta.adset.budget.update",
    params: { adSetId: "as_1", dailyBudget: 100 },
    riskLevel: "FINANCIAL",
    state: "WAITING_CONFIRMATION",
    approvalId: "ap-1",
    expiresAt: new Date(Date.now() + 120_000).toISOString(),
    createdAt: new Date().toISOString(),
  };
}

/** A pending-action port with one active action in every conversation. */
function pendingActions(options: { confirmSucceeds?: boolean } = {}): PendingActionPort {
  const confirmSucceeds = options.confirmSucceeds ?? true;
  return {
    async getActivePendingAction(conversationId: string) {
      return pendingActionFor(conversationId);
    },
    async confirmPendingAction(conversationId: string) {
      return confirmSucceeds
        ? { success: true, pendingAction: pendingActionFor(conversationId), message: "Approved." }
        : { success: false, message: "That action has expired." };
    },
    async rejectPendingAction() {
      return { success: true, message: "Cancelled." };
    },
    async modifyPendingAction(conversationId: string, _userId: string, params: Record<string, unknown>) {
      return {
        pendingAction: { ...pendingActionFor(conversationId), params: { ...pendingActionFor(conversationId).params, ...params } },
        message: "Updated. Confirm to proceed.",
      };
    },
  } as unknown as PendingActionPort;
}

function taskConversation(options: { throws?: boolean } = {}) {
  const inputs: Array<Parameters<TaskConversationPort["handle"]>[0]> = [];
  const port: TaskConversationPort = {
    async handle(input) {
      inputs.push(input);
      if (options.throws) throw new Error("task service unavailable");
      return { message: `Done — I ran system.status for "${input.goal}".`, taskId: "task-1" };
    },
  };
  return { port, inputs };
}

function router(deps: Partial<ChatRouterDeps> & { conversationRepo: ConversationStorePort }) {
  return createChatRouter({
    tokenService,
    orchestrator: answeringOrchestrator().orchestrator,
    executor: unreachableExecutor,
    googleWrites: null,
    ...deps,
  });
}

/** POST /, resolved when the route answers. */
function postChat(
  chatRouter: ReturnType<typeof createChatRouter>,
  body: Record<string, unknown>
): Promise<{ status: number; body: { success: boolean; traceId?: string; data?: { conversationId?: string } } & Record<string, unknown> }> {
  return new Promise((resolve) => {
    const headers: Record<string, string> = { authorization: "Bearer token-user-1" };
    const req = {
      method: "POST",
      path: "/",
      url: "/",
      headers,
      body,
      params: {},
      query: {},
      ip: "127.0.0.1",
      get: (name: string) => headers[name.toLowerCase()],
    } as never;
    const res = {
      statusCode: 200,
      status(code: number) {
        this.statusCode = code;
        return this;
      },
      json(payload: unknown) {
        resolve({ status: this.statusCode, body: payload as never });
        return this;
      },
      setHeader() {
        return this;
      },
    };
    const layer = (
      chatRouter as unknown as {
        stack: Array<{ route?: { path: string; methods: Record<string, boolean>; stack: Array<{ handle: (...args: unknown[]) => void }> } }>;
      }
    ).stack.find((l) => l.route?.path === "/" && l.route.methods.post);
    const handlers = layer!.route!.stack.map((s) => s.handle);
    let index = 0;
    const next = () => {
      if (index < handlers.length) handlers[index++]!(req, res, next);
    };
    next();
  });
}

/** Start a conversation on the plain orchestrator path and return its id. */
async function openConversation(
  store: ReturnType<typeof memoryConversationStore>
): Promise<string> {
  const opened = await postChat(router({ conversationRepo: store.store }), { message: "Hello" });
  return opened.body.data!.conversationId!;
}

// ---------------------------------------------------------------------------
// A. Orchestrator path
// ---------------------------------------------------------------------------

describe("A. the orchestrator path stores the traceId on the user message", () => {
  it("saves the response's traceId in the user message metadata", async () => {
    const store = memoryConversationStore();
    const res = await postChat(router({ conversationRepo: store.store }), { message: "Hello JARVIS" });

    const [user] = store.all().filter((m) => m.role === "user");
    expect(res.status).toBe(200);
    expect(typeof res.body.traceId).toBe("string");
    expect(user!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("uses the same traceId the orchestrator received", async () => {
    const store = memoryConversationStore();
    const { orchestrator, seen } = answeringOrchestrator();
    await postChat(router({ conversationRepo: store.store, orchestrator }), { message: "Hello JARVIS" });

    const [user] = store.all().filter((m) => m.role === "user");
    expect(user!.metadata?.traceId).toBe(seen[0]!.context.traceId);
  });

  it("leaves the user's words exactly as they were sent", async () => {
    const store = memoryConversationStore();
    const text = "  Meta mein campaign ka budget ₹50,000 hai — kya karein?  ";
    await postChat(router({ conversationRepo: store.store }), { message: text });

    const [user] = store.all().filter((m) => m.role === "user");
    expect(user!.content).toBe(text);
  });

  it("never takes the traceId from the request body", async () => {
    const store = memoryConversationStore();
    const res = await postChat(router({ conversationRepo: store.store }), {
      message: "Hello JARVIS",
      metadata: { traceId: "client-forged-trace" },
    });

    const [user] = store.all().filter((m) => m.role === "user");
    expect(user!.metadata?.traceId).toBe(res.body.traceId);
    expect(user!.metadata?.traceId).not.toBe("client-forged-trace");
  });
});

// ---------------------------------------------------------------------------
// B. Task path
// ---------------------------------------------------------------------------

describe("B. the Task path stores the traceId on the user message", () => {
  it("saves it for a work request that runs", async () => {
    const store = memoryConversationStore();
    const tasks = taskConversation();
    const res = await postChat(
      router({ conversationRepo: store.store, taskConversation: tasks.port }),
      { message: "check my system status" }
    );

    const [user] = store.all().filter((m) => m.role === "user");
    expect(tasks.inputs).toHaveLength(1);
    expect(user!.metadata).toEqual({ traceId: res.body.traceId });
    expect(tasks.inputs[0]!.traceId).toBe(res.body.traceId);
  });

  it("saves it when the time is too vague and nothing runs", async () => {
    const store = memoryConversationStore();
    const tasks = taskConversation();
    const res = await postChat(
      router({ conversationRepo: store.store, taskConversation: tasks.port }),
      { message: "check my system status later" }
    );

    const [user] = store.all().filter((m) => m.role === "user");
    expect(tasks.inputs).toHaveLength(0);
    expect(user!.metadata).toEqual({ traceId: res.body.traceId });
  });
});

// ---------------------------------------------------------------------------
// C. Pending-action branches
// ---------------------------------------------------------------------------

describe("C. the pending-action branches store the traceId on the user message", () => {
  it("CONFIRM: saves it, and the execution runs under the same trace", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);
    const exec = recordingExecutor();

    const res = await postChat(
      router({ conversationRepo: store.store, pendingActionService: pendingActions(), executor: exec.executor }),
      { message: "yes", conversationId }
    );

    const confirm = store.usersOf(conversationId).find((m) => m.content === "yes");
    expect(confirm!.metadata).toEqual({ traceId: res.body.traceId });
    expect(exec.requests[0]!.traceId).toBe(res.body.traceId);
  });

  it("CONFIRM that could not be approved: still saves it", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);

    const res = await postChat(
      router({ conversationRepo: store.store, pendingActionService: pendingActions({ confirmSucceeds: false }) }),
      { message: "yes", conversationId }
    );

    const confirm = store.usersOf(conversationId).find((m) => m.content === "yes");
    expect(confirm!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("REJECT: saves it", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);

    const res = await postChat(
      router({ conversationRepo: store.store, pendingActionService: pendingActions() }),
      { message: "no", conversationId }
    );

    const reject = store.usersOf(conversationId).find((m) => m.content === "no");
    expect(reject!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("MODIFY: saves it", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);

    const res = await postChat(
      router({ conversationRepo: store.store, pendingActionService: pendingActions() }),
      { message: "make it ₹200/day", conversationId }
    );

    const modify = store.usersOf(conversationId).find((m) => m.content === "make it ₹200/day");
    expect(modify!.metadata).toEqual({ traceId: res.body.traceId });
  });
});

// ---------------------------------------------------------------------------
// D. Failed requests
// ---------------------------------------------------------------------------

describe("D. a failed request keeps the traceId on the user message it saved", () => {
  it("orchestrator failure: the user message carries it and no reply is stored", async () => {
    const store = memoryConversationStore();
    const res = await postChat(
      router({ conversationRepo: store.store, orchestrator: failingOrchestrator() }),
      { message: "How are my campaigns doing?" }
    );

    expect(res.body.success).toBe(false);
    const saved = store.all();
    expect(saved.map((m) => m.role)).toEqual(["user"]);
    expect(saved[0]!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("orchestrator throws: the user message carries the traceId of the 500", async () => {
    const store = memoryConversationStore();
    const res = await postChat(
      router({ conversationRepo: store.store, orchestrator: throwingOrchestrator() }),
      { message: "How are my campaigns doing?" }
    );

    expect(res.status).toBe(500);
    const [user] = store.all().filter((m) => m.role === "user");
    expect(user!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("Task path throws: the user message carries the traceId of the 500", async () => {
    const store = memoryConversationStore();
    const res = await postChat(
      router({ conversationRepo: store.store, taskConversation: taskConversation({ throws: true }).port }),
      { message: "check my system status" }
    );

    expect(res.status).toBe(500);
    const [user] = store.all().filter((m) => m.role === "user");
    expect(user!.metadata).toEqual({ traceId: res.body.traceId });
  });

  it("a request refused before anything is saved stores nothing", async () => {
    const store = memoryConversationStore();
    const res = await postChat(router({ conversationRepo: store.store }), {
      message: "Hello",
      conversationId: "conv-that-does-not-exist",
    });

    expect(res.status).toBe(404);
    expect(store.all()).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// E. Assistant messages are unchanged
// ---------------------------------------------------------------------------

describe("E. the assistant message keeps its existing traceId behaviour", () => {
  it("orchestrator path: `{ model, traceId }`, same trace as the user message", async () => {
    const store = memoryConversationStore();
    const res = await postChat(router({ conversationRepo: store.store }), { message: "Hello JARVIS" });

    const [user, assistant] = store.all();
    expect(assistant!.role).toBe("assistant");
    expect(Object.keys(assistant!.metadata ?? {}).sort()).toEqual(["model", "traceId"]);
    expect(assistant!.metadata?.traceId).toBe(res.body.traceId);
    expect(assistant!.metadata?.traceId).toBe(user!.metadata?.traceId);
  });

  it("Task path: `{ traceId, taskId }`, same trace as the user message", async () => {
    const store = memoryConversationStore();
    const res = await postChat(
      router({ conversationRepo: store.store, taskConversation: taskConversation().port }),
      { message: "check my system status" }
    );

    const [user, assistant] = store.all();
    expect(assistant!.metadata).toEqual({ traceId: res.body.traceId, taskId: "task-1" });
    expect(user!.metadata?.traceId).toBe(assistant!.metadata?.traceId);
  });

  it("CONFIRM: `{ traceId, pendingActionId, executionStatus }`", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);
    const res = await postChat(
      router({
        conversationRepo: store.store,
        pendingActionService: pendingActions(),
        executor: recordingExecutor().executor,
      }),
      { message: "yes", conversationId }
    );

    const reply = store.of(conversationId).at(-1)!;
    expect(reply.role).toBe("assistant");
    expect(reply.metadata).toEqual({
      traceId: res.body.traceId,
      pendingActionId: "pa-1",
      executionStatus: "completed",
    });
  });
});

// ---------------------------------------------------------------------------
// J. Concurrent requests
// ---------------------------------------------------------------------------

describe("J. concurrent requests cannot cross-link", () => {
  it("two overlapping sends in one conversation each keep their own traceId", async () => {
    const store = memoryConversationStore();
    const conversationId = await openConversation(store);

    // The first turn is held open until the second has been saved, which is
    // exactly the interleaving that makes message ORDER an unreliable link:
    // user, user, assistant, assistant.
    let releaseFirst!: () => void;
    const firstHeld = new Promise<void>((resolve) => (releaseFirst = resolve));
    const orchestrator: IOrchestrator = {
      async process(request, context): Promise<JarvisResponse> {
        if (request.message === "first") await firstHeld;
        return {
          success: true,
          data: { message: `reply to ${request.message}`, conversationId: context.conversationId ?? "" },
          traceId: context.traceId,
          timestamp: new Date().toISOString(),
        };
      },
    };
    const chat = router({ conversationRepo: store.store, orchestrator });

    const first = postChat(chat, { message: "first", conversationId });
    const second = await postChat(chat, { message: "second", conversationId });
    releaseFirst();
    const firstRes = await first;

    const turn = store.of(conversationId).slice(2);
    expect(turn.map((m) => `${m.role}:${m.content}`)).toEqual([
      "user:first",
      "user:second",
      "assistant:reply to second",
      "assistant:reply to first",
    ]);

    const byContent = (content: string) => turn.find((m) => m.content === content)!;
    expect(firstRes.body.traceId).not.toBe(second.body.traceId);
    expect(byContent("first").metadata?.traceId).toBe(firstRes.body.traceId);
    expect(byContent("second").metadata?.traceId).toBe(second.body.traceId);
    expect(byContent("reply to first").metadata?.traceId).toBe(firstRes.body.traceId);
    expect(byContent("reply to second").metadata?.traceId).toBe(second.body.traceId);
  });

  it("every request gets a fresh traceId", async () => {
    const store = memoryConversationStore();
    const chat = router({ conversationRepo: store.store });

    const traces = new Set<string>();
    for (let i = 0; i < 5; i++) {
      const res = await postChat(chat, { message: `hello ${i}` });
      traces.add(res.body.traceId!);
    }

    expect(traces.size).toBe(5);
    const stored = store.all().filter((m) => m.role === "user").map((m) => m.metadata?.traceId);
    expect(new Set(stored)).toEqual(traces);
  });
});

// ---------------------------------------------------------------------------
// F. End to end: the stored traceId never reaches the model
// ---------------------------------------------------------------------------

class CapturingProvider implements IAIProvider {
  readonly id = "capturing-ai";
  readonly name = "Capturing AI";
  readonly defaultModel = "capturing-model";
  readonly requests: AICompletionRequest[] = [];

  async complete(request: AICompletionRequest): Promise<AICompletionResponse> {
    this.requests.push(request);
    return { message: { role: "assistant", content: "noted" }, finishReason: "stop", model: this.defaultModel };
  }
  async listModels(): Promise<string[]> {
    return [this.defaultModel];
  }
  async isAvailable(): Promise<boolean> {
    return true;
  }
}

const silentAudit = {
  async log(_entry: Omit<AuditEntry, "id" | "timestamp">) {},
  async query() {
    return [];
  },
} as unknown as AuditLogger;

describe("F. history rebuilt from stored messages does not show the traceId to the model", () => {
  it("the second turn's model request carries the first turn's words but not its traceId", async () => {
    const store = memoryConversationStore();
    const provider = new CapturingProvider();
    const registry = new AgentRegistry();
    registry.register(new ConversationalAssistant({ provider, systemPrompt: "You are JARVIS." }));
    const orchestrator = new Orchestrator(registry, unreachableExecutor, silentAudit, {});
    const chat = router({ conversationRepo: store.store, orchestrator });

    const first = await postChat(chat, { message: "Remember the word pineapple" });
    const conversationId = first.body.data!.conversationId!;
    await postChat(chat, { message: "What word did I say?", conversationId });

    const firstTrace = first.body.traceId!;
    const stored = store.usersOf(conversationId)[0]!;
    expect(stored.metadata?.traceId).toBe(firstTrace);

    const secondTurn = provider.requests.at(-1)!;
    const modelVisible = JSON.stringify(secondTurn.messages);

    // Positive control: the history IS in front of the model...
    expect(modelVisible).toContain("Remember the word pineapple");
    // ...and its correlation metadata is not.
    expect(modelVisible).not.toContain(firstTrace);
    expect(modelVisible).not.toContain("traceId");
    for (const message of secondTurn.messages) {
      expect(Object.keys(message).sort()).toEqual(["content", "role"]);
    }
    expect(secondTurn.traceId).not.toBe(firstTrace);
  });
});
